#!/usr/bin/env bash
python3 "$(git rev-parse --show-toplevel)/scripts/pending-lint.py" . || exit 1
python3 "$(git rev-parse --show-toplevel)/scripts/queue-lint.py" . || exit 1
python3 "$(git rev-parse --show-toplevel)/scripts/css-lint.py" . || exit 1
